// flow-typed signature: 0fe99f2c956577618fbc261cbd46c1b1
// flow-typed version: <<STUB>>/bunyan-middleware_v^0.5.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bunyan-middleware/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bunyan-middleware/example.js' {
  declare module.exports: $Exports<'bunyan-middleware/example'>;
}
declare module 'bunyan-middleware/index' {
  declare module.exports: $Exports<'bunyan-middleware'>;
}
declare module 'bunyan-middleware/index.js' {
  declare module.exports: $Exports<'bunyan-middleware'>;
}
