// flow-typed signature: 752aa5b2f1cf1cce6c1e939112676bf2
// flow-typed version: <<STUB>>/phone-formatter_v0.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phone-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'phone-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phone-formatter/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phone-formatter/index' {
  declare module.exports: $Exports<'phone-formatter'>;
}
declare module 'phone-formatter/index.js' {
  declare module.exports: $Exports<'phone-formatter'>;
}
declare module 'phone-formatter/test/test.js' {
  declare module.exports: $Exports<'phone-formatter/test/test'>;
}
